# Copyright (c) 2016 Jonathan Lloyd - copyright@thisisjonathan.com
#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""Lists of words for use in idea templates"""

ADJECTIVES = [
    'scary',
    'challenging',
    'slow-paced',
    'relaxing',
    'twitchy',
    'mysterious',
    'colourful',
    'silly',
    'comedic',
    'retro',
    'pixel',
    'generative',
    'stealthy',
    'minimalistic',
    'zen-like',
    'quirky',
    'rogue-like',
    'turn based',
    'side-scrolling',
    'multiplayer',
    'co-op',
    'first-person',
    'virtual reality',
]

GENRES = [
    'platformer',
    'shooter',
    'stealth',
    'fighting',
    'adventure',
    'text-adventure',
    'role-playing',
    'simulation',
    'strategy',
    'casual',
    'puzzle',
    'racing',
    'board',
    'rhythm',
    'tower defense',
    'beat-em-up',
]

CHARACTERS = [
    'anti-hero',
    'vigilante',
    'soldier',
    'italian plumber',
    'dragon',
    'super hero',
    'super soldier',
    'hacker',
    'child',
    'explorer',
    'introvert',
    'poet',
    'boy',
    'girl',
    'thief',
    'spy',
    'trained assassin',
    'ninja',
    'samurai',
    'trickster',
    'king',
    'queen',
    'princess',
    'time traveller',
    'mad scientist',
    'alien',
    'cyborg',
    'astronaut',
    'blue hedgehog',
    'villain',
    'wizard',
    'sorceress',
    'witch',
    'vampire',
]

CHARACTER_ADJECTIVES = [
    'outlaw',
    'renegade',
    'vengeful',
    'rollerskating',
    'motorbike-riding',
    'superintelligent',
    'robotic',
    'virtual',
    'space-faring',
    'sea-faring',
    'destitute',
    'reckless',
    'incompetant',
    'lovelorn',
    'flamboyant',
    'wise-cracking',
    'mischievous',
    'fourth wall breaking',
    'reactionary',
    'spell-casting',
]

THINGS = [
    'planet',
    'castle',
    'totalitarian regime',
    'alien planet',
    'map',
    'government',
    'society',
    'player',
    'army',
    'underground pipe network',
    'battlefield',
    'heard of cats',
    'russian author',
    'cell phone',
    'magical ring',
    'magical power',
    'enchanted rune',
    'plasma gun',
    'improvised weapon',
    'mountain',
    'forest',
    'ocean',
    'lost city',
    'floating raft city',
    'floating sky city',
    'flag',
]

PRESENT_VERBS = [
    'escapes',
    'fights',
    'must destroy',
    'avoids',
    'controls',
    'explores the deeper meaning of',
]

ACTIONS = [
    'press the spacebar',
    'twitch your mouse',
    'fire your weapon',
    'die',
    'jump over something',
    'walk backwards',
    'cast a spell',
    'jump on some platforms',
    'use mind control',
    'solve a platforming puzzle',
    'quit the game',
    'move to the beat',
    'progress',
    'live',
    'move things with your mind',
    'transform into any character',
    'hack into a website',
    'score points',
    'collect items',
    'use motion controls',
    'lose health',
    'touch the walls',
    'turn back time',
    'jump on enemies',
    'craft items',
    'build a shelter',
    'solve mind-bending puzzles',
    'rewind time',
    'avoid enemies',
    'protect your base',
    'sweep enemy bases',
    'capture enemies',
]

ART_STYLES = [
    'pixel-art',
    'voxel',
    'vector',
    'stop motion',
    'glitch',
    'low-poly',
    '3D',
    '2D',
    'film noir',
    'b-movie',
    '80s SciFi',
    'low budget',
    'cartoonish',
    'hand illustrated',
    'steampunk',
    'dieselpunk',
    'victorian',
    'cyperpunk',
    'neon',
    'water colour',
    'fairytale',
    'gothic',
    'isometric',
    'psychedelic',
    'abstract',
    'post-apocalyptic',
    'dystopian',
    'under water',
    'medieval',
]

SETTINGS = [
    'computer',
    'castle',
    'office',
    'hotel',
    'school',
    'church',
    'junkyard',
    'science lab',
    'casino',
    'factory',
    'nightclub',
    'cave',
    'spaceship',
    'artificial space habitat',
    'abandoned mental asylum',
    'haunted house',
    'school for witches and wizards',
    'school for mutants',
    'secret government science lab',
    'theatre',
]

HASHTAGS = [
    'gamedev',
    'indiedev',
    'indiegame',
    'indiegames',
    'indie',
    'gameart',
    'indiegamedev',
    'gameideas',
    'gameidea',
]
